version: '3' #使用docker-compose版本
services: #服务
  nuxt-container: #
    container_name: new-netchina-ui
    user: "root"
    build: . #Dockerfile源码编译
    restart: always #异常退出后自动重启服务
    command: ["pm2-runtime","start","ecosystem.config.js"]
    ports:
      - "3000:3000"